### ISSUE TITLE
[https] Fix mixed content on ringojs.org

### ISSUE THREAD

**Issue by botic** [ringo/ringojs.org#12]

**Comment by botic** [comment]
@oberhamsi Your script still uses http `http://stats.nekapuzer.at/hit/` and is not reachable yet. Can we remove it? Any alternatives like Piwik?

**Comment by oberhamsi** [comment]
yes, please remove it for now. i didn't have time to keep ositestats up2date

**Comment by botic** [comment]
wontfix
